/**
 * Build the nginx `map` body for redirects (used by sync-redirects.mjs).
 *
 * nginx map semantics this relies on:
 *   - exact string keys are matched case-insensitively and must be unique ignoring case;
 *   - exact keys are checked before regex keys; regexes are tried in order.
 * So: exact keys only for real redirects, and category letter-case normalisation via a
 * regex that matches every casing *except* the canonical lowercase URL (no loops).
 */

// Characters that would break or be interpreted inside an nginx quoted string.
const SAFE_PATH = /^\/[^\s"'$\\{};]*$/;
const SAFE_TARGET = /^(\/|https?:\/\/)[^\s"'$\\{};]*$/;
const q = (s) => `"${s}"`;
const reEscape = (s) => s.replace(/[.*+?()[\]|^]/g, '\\$&');
const trimSlash = (p) => (p.length > 1 ? p.replace(/\/+$/, '') : p);

export function buildMap(redirects, categories, warn = () => {}) {
  const exact = new Map(); // lowercased key -> [key, target]
  const regex = [];

  for (const r of redirects) {
    if (!SAFE_PATH.test(r.from_path) || !SAFE_TARGET.test(r.to_path)) {
      warn(`skipping unsafe redirect ${JSON.stringify(r)}`);
      continue;
    }
    const from = trimSlash(r.from_path);
    if (from === '/') continue;
    // A redirect that only changes letter case (e.g. /category/Chair-stretcher → /category/chair-stretcher)
    // would also match the target itself, because exact keys are case-insensitive. Category casing
    // is handled by the regex below instead.
    if (r.to_path.startsWith('/') && trimSlash(r.to_path).toLowerCase() === from.toLowerCase()) continue;

    for (const key of [from, `${from}/`]) {
      if (exact.has(key.toLowerCase())) {
        warn(`skipping duplicate redirect key ${key}`);
        continue;
      }
      exact.set(key.toLowerCase(), [key, r.to_path]);
    }
    // Belt and braces in case exact matching is case-sensitive on some nginx builds.
    if (from.startsWith('/category/') && !from.includes('?')) regex.push([`~*^${reEscape(from)}/?$`, r.to_path]);
  }

  // Category URLs are lowercase. Redirect any other casing to the lowercase URL; the negative
  // lookahead (case-sensitive) lets the exact lowercase URL through untouched.
  for (const { slug } of categories) {
    const lower = String(slug).toLowerCase();
    if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(lower)) continue;
    const canonical = `/category/${lower}`;
    if (exact.has(canonical)) continue;
    regex.push([`~^/category/(?!${reEscape(lower)}/?$)(?i:${reEscape(lower)})/?$`, canonical]);
  }

  const lines = ['# Generated by scripts/sync-redirects.mjs — do not edit by hand.'];
  for (const [key, to] of [...exact.values()].sort(([a], [b]) => a.localeCompare(b))) lines.push(`${q(key)} ${q(to)};`);
  for (const [pattern, to] of regex) lines.push(`${q(pattern)} ${q(to)};`);
  return `${lines.join('\n')}\n`;
}
