#!/usr/bin/env bash
# One-time setup on the droplet: serve the Supabase `redirects` table as real HTTP 301s
# from nginx (works behind Cloudflare without any Cloudflare access).
#
#   sudo bash scripts/setup-nginx-redirects.sh
#
# Installs:
#   /etc/nginx/conf.d/mrbedmed-redirects.conf   map $uri -> redirect target (http context)
#   /etc/nginx/mrbedmed-redirects.map           generated by scripts/sync-redirects.mjs
#   an `if ($mrbedmed_redirect)` line in the server block(s) that serve this app
#   /etc/cron.d/mrbedmed-redirects               re-sync every minute
# Every edited file is backed up; if `nginx -t` fails, everything is restored.
# Safe to re-run.
set -euo pipefail

APP_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CONF=/etc/nginx/conf.d/mrbedmed-redirects.conf
# Must load before every `map` block in nginx (the first map fixes the hash size), hence "00-".
HASH_CONF=/etc/nginx/conf.d/00-mrbedmed-map-hash.conf
MAP=/etc/nginx/mrbedmed-redirects.map
CRON=/etc/cron.d/mrbedmed-redirects
LOG=/var/log/mrbedmed-redirects.log
MARKER='mrbedmed_redirect'
BACKUP="/root/nginx-backup-$(date +%Y%m%d-%H%M%S)"

log() { printf '\n\033[1;34m== %s\033[0m\n' "$*"; }
ok()  { printf '\033[1;32m   ok: %s\033[0m\n' "$*"; }
die() { printf '\n\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

[ "$(id -u)" = 0 ] || die "run as root (sudo)"
command -v nginx >/dev/null || die "nginx not found"
NODE="$(command -v node)" || die "node not found"
[ -f "$APP_DIR/.env" ] || die "$APP_DIR/.env missing"

log "1/5 Locate the nginx site serving $APP_DIR"
mapfile -t SITES < <(grep -lRsE "^[[:space:]]*(root|alias)[[:space:]]+$APP_DIR(/|;|[[:space:]])" /etc/nginx/sites-enabled 2>/dev/null | xargs -r -n1 readlink -f | sort -u)
[ "${#SITES[@]}" -gt 0 ] || die "no nginx config references $APP_DIR (looked in sites-enabled and conf.d)"
for f in "${SITES[@]}"; do ok "site config: $f"; done
grep -qsE '^\s*include\s+/etc/nginx/conf\.d/\*\.conf' /etc/nginx/nginx.conf || die "/etc/nginx/nginx.conf does not include conf.d/*.conf"

mkdir -p "$BACKUP"
for f in "${SITES[@]}" "$CONF" "$MAP" "$HASH_CONF"; do [ -f "$f" ] && cp -a --parents "$f" "$BACKUP"; done
ok "backup in $BACKUP"

restore() {
  printf '\033[1;31m   restoring nginx config from %s\033[0m\n' "$BACKUP" >&2
  local site
  for site in "${SITES[@]}"; do [ -f "$BACKUP$site" ] && cp -a "$BACKUP$site" "$site"; done
  if [ -f "$BACKUP$CONF" ]; then cp -a "$BACKUP$CONF" "$CONF"; else rm -f "$CONF"; fi
  [ -f "$BACKUP$MAP" ] && cp -a "$BACKUP$MAP" "$MAP"
  if [ -f "$BACKUP$HASH_CONF" ]; then cp -a "$BACKUP$HASH_CONF" "$HASH_CONF"; else rm -f "$HASH_CONF"; fi
  nginx -t >/dev/null 2>&1 && nginx -s reload || true
}

log "2/5 Generate the redirect map"
[ -f "$MAP" ] || : > "$MAP"
REDIRECTS_MAP_FILE="$MAP" NO_RELOAD=1 "$NODE" "$APP_DIR/scripts/sync-redirects.mjs" || die "could not fetch redirects from Supabase"
ok "$(grep -c '^"' "$MAP") map entries"

log "3/5 Install map + server-block rule"
# Long keys (ID and blog URLs) exceed nginx's default map hash bucket. map_hash_bucket_size /
# map_hash_max_size are http-level, may be set only once, and must come before the first `map`
# block anywhere in the config (other sites' conf.d files have maps). So they live in their own
# file that loads first, and only if no other config already sets them.
HASH_LINES=""
for directive in "map_hash_bucket_size 256" "map_hash_max_size 8192"; do
  name="${directive%% *}"
  if grep -RqsE "^[[:space:]]*$name[[:space:]]" /etc/nginx --exclude="$(basename "$HASH_CONF")" --exclude="$(basename "$CONF")"; then
    printf '\033[1;33m   note: %s is already set in another nginx config; leaving it (raise it there if nginx -t complains)\033[0m\n' "$name"
  else
    HASH_LINES="$HASH_LINES$directive;"$'\n'
  fi
done
if [ -n "$HASH_LINES" ]; then
  printf '# Managed by %s/scripts/setup-nginx-redirects.sh (loads before every map).\n%s' "$APP_DIR" "$HASH_LINES" > "$HASH_CONF"
  ok "$HASH_CONF"
else
  rm -f "$HASH_CONF"
fi

cat > "$CONF" <<EOF
# Managed by $APP_DIR/scripts/setup-nginx-redirects.sh
map \$uri \$$MARKER {
    default "";
    include $MAP;
}
EOF
ok "$CONF"

RULE='    if ($mrbedmed_redirect) { return 301 $mrbedmed_redirect$is_args$args; }'
for f in "${SITES[@]}"; do
  if grep -q "$MARKER" "$f"; then ok "rule already present in $f"; continue; fi
  # Insert the rule into each server { } block that serves the app, right after server_name.
  awk -v app="$APP_DIR" -v rule="$RULE" '
    function flush(   i, done) {
      done = 0
      for (i = 1; i <= n; i++) {
        print buf[i]
        if (!done && has_app && buf[i] ~ /^[ \t]*server_name[ \t]/) { print rule; done = 1 }
      }
      n = 0; has_app = 0; inblock = 0
    }
    {
      line = $0
      if (!inblock && line ~ /^[ \t]*server[ \t]*\{/) { inblock = 1; depth = 0; n = 0; has_app = 0 }
      if (inblock) {
        buf[++n] = line
        if (index(line, app)) has_app = 1
        tmp = line; sub(/#.*/, "", tmp)
        depth += gsub(/\{/, "{", tmp) - gsub(/\}/, "}", tmp)
        if (depth == 0) flush()
        next
      }
      print line
    }
    END { if (n) flush() }
  ' "$f" > "$f.mrbedmed.tmp"
  if cmp -s "$f" "$f.mrbedmed.tmp"; then
    rm -f "$f.mrbedmed.tmp"
    printf '\033[1;33m   skipped: no server block serving the app in %s\033[0m\n' "$f"
    continue
  fi
  cat "$f.mrbedmed.tmp" > "$f" && rm -f "$f.mrbedmed.tmp"
  ok "rule added to $f"
done

log "4/5 Test and reload nginx"
if ! nginx -t; then restore; die "nginx -t failed; original config restored"; fi
nginx -s reload
ok "nginx reloaded"

log "5/5 Cron: re-sync every minute"
cat > "$CRON" <<EOF
# Sync Supabase redirects into nginx (managed by setup-nginx-redirects.sh)
* * * * * root $NODE $APP_DIR/scripts/sync-redirects.mjs >> $LOG 2>&1
EOF
chmod 644 "$CRON"
ok "$CRON"

printf '\n   Check (expect 301 + location):\n'
sleep 2; curl -sI --max-time 10 "https://mrbedmed.com/category/ICU-beds" | grep -iE '^(HTTP|location)' | sed 's/^/     /' || true
printf '\n\033[1;32mDone.\033[0m Redirects added in Dashboard → Redirects go live within a minute.\n'
printf 'Undo: restore files from %s, then rm %s %s && nginx -s reload\n' "$BACKUP" "$CONF" "$CRON"
